In [1]:
import pandas as pd
import numpy as np
import netCDF4 as nc
import xarray as xr
import re
import pyreadr

In [2]:
data_dir = '../data/'

# PM 2.5

## Kuwait

In [3]:
kwt_pm25 = pd.read_csv(data_dir + 'kwt_pm25.csv')

In [4]:
kwt_pm25.head()

date  latitude  longitude   pm25    bc   uvc   dc  oc  ec  tc  ...  \
0  2017-10-25   29.3217    47.9719  35.36  4.36  3.63  0.0 NaN NaN NaN  ...   
1  2017-10-26   29.3217    47.9719  67.46  4.97  4.43  0.0 NaN NaN NaN  ...   
2  2017-10-27   29.3217    47.9719  66.23  4.12  3.72  0.0 NaN NaN NaN  ...   
3  2017-10-28   29.3217    47.9719  41.48  2.44  2.14  0.0 NaN NaN NaN  ...   
4  2017-10-29   28.9570    48.1548  39.30  1.89  1.67  0.0 NaN NaN NaN  ...   

       Ce      Sm   Eu   Tb       W      Au      Hg      Tl      Pb    pm10  
0  0.0071  0.0336  0.0  0.0  0.0000  0.0000  0.0000  0.0000  0.0291  138.10  
1  0.0000  0.0000  0.0  0.0  0.0000  0.0000  0.0000  0.0011  0.0125  189.06  
2  0.0000  0.0134  0.0  0.0  0.0000  0.0000  0.0013  0.0000  0.0226  147.97  
3  0.0000  0.0000  0.0  0.0  0.0022  0.0000  0.0000  0.0001  0.0125   88.43  
4  0.0176  0.0489  0.0  0.0  0.0005  0.0143  0.0000  0.0034  0.0208   72.86  

[5 rows x 68 columns]

In [5]:
kwt_pm25.columns

Index(['date', 'latitude', 'longitude', 'pm25', 'bc', 'uvc', 'dc', 'oc', 'ec',
       'tc', 'oc1', 'oc2', 'oc3', 'oc4', 'pyrolC', 'ec1', 'ec2', 'ec3',
       'optEC', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'K', 'Ca', 'Sc', 'Ti',
       'V', 'Cr', 'Mn', 'Fe', 'Co', 'Ni', 'Cu', 'Zn', 'Ga', 'Ge', 'As', 'Se',
       'Br', 'Rb', 'Sr', 'Y', 'Zr', 'Nb', 'Mo', 'Pd', 'Ag', 'Cd', 'In', 'Sn',
       'Sb', 'Cs', 'Ba', 'La', 'Ce', 'Sm', 'Eu', 'Tb', 'W', 'Au', 'Hg', 'Tl',
       'Pb', 'pm10'],
      dtype='object')

In [6]:
kwt_pm25.shape

(5473, 68)

In [7]:
kwt_pm25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5473 entries, 0 to 5472
Data columns (total 68 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       5473 non-null   object 
 1   latitude   5473 non-null   float64
 2   longitude  5473 non-null   float64
 3   pm25       3559 non-null   float64
 4   bc         4319 non-null   float64
 5   uvc        4155 non-null   float64
 6   dc         4155 non-null   float64
 7   oc         786 non-null    float64
 8   ec         788 non-null    float64
 9   tc         530 non-null    float64
 10  oc1        530 non-null    float64
 11  oc2        530 non-null    float64
 12  oc3        530 non-null    float64
 13  oc4        530 non-null    float64
 14  pyrolC     530 non-null    float64
 15  ec1        530 non-null    float64
 16  ec2        530 non-null    float64
 17  ec3        530 non-null    float64
 18  optEC      530 non-null    float64
 19  Na         4374 non-null   float64
 20  Mg      

In [8]:
kwt_pm25['date'] = pd.to_datetime(kwt_pm25['date'])

In [9]:
kwt_pm25.head()

date  latitude  longitude   pm25    bc   uvc   dc  oc  ec  tc  ...  \
0 2017-10-25   29.3217    47.9719  35.36  4.36  3.63  0.0 NaN NaN NaN  ...   
1 2017-10-26   29.3217    47.9719  67.46  4.97  4.43  0.0 NaN NaN NaN  ...   
2 2017-10-27   29.3217    47.9719  66.23  4.12  3.72  0.0 NaN NaN NaN  ...   
3 2017-10-28   29.3217    47.9719  41.48  2.44  2.14  0.0 NaN NaN NaN  ...   
4 2017-10-29   28.9570    48.1548  39.30  1.89  1.67  0.0 NaN NaN NaN  ...   

       Ce      Sm   Eu   Tb       W      Au      Hg      Tl      Pb    pm10  
0  0.0071  0.0336  0.0  0.0  0.0000  0.0000  0.0000  0.0000  0.0291  138.10  
1  0.0000  0.0000  0.0  0.0  0.0000  0.0000  0.0000  0.0011  0.0125  189.06  
2  0.0000  0.0134  0.0  0.0  0.0000  0.0000  0.0013  0.0000  0.0226  147.97  
3  0.0000  0.0000  0.0  0.0  0.0022  0.0000  0.0000  0.0001  0.0125   88.43  
4  0.0176  0.0489  0.0  0.0  0.0005  0.0143  0.0000  0.0034  0.0208   72.86  

[5 rows x 68 columns]

In [10]:
kwt_pm25['date'].describe()

count                             5473
mean     2015-05-03 00:51:18.384798208
min                2004-02-20 00:00:00
25%                2017-11-03 00:00:00
50%                2018-03-21 00:00:00
75%                2018-11-23 00:00:00
max                2020-04-01 00:00:00
Name: date, dtype: object

## Qatar

In [11]:
qatar_pm25 = pd.read_csv(data_dir + 'qatar_pm25.csv')

In [12]:
qatar_pm25.head()

pms       location   sample_id  sample_id1 sample_type  Start_Date  \
0  PM2.5  Qatar-Ambient  DOH-001-MS  DOH-001-QZ         NaN  02/06/2020   
1  PM2.5  Qatar-Ambient  DOH-005-MS         NaN         NaN  02/10/2020   
2  PM2.5  Qatar-Ambient  DOH-003-MS  DOH-002-QZ         NaN  02/12/2020   
3  PM2.5  Qatar-Ambient  DOH-007-MS  DOH-004-QZ         NaN  02/14/2020   
4  PM2.5  Qatar-Ambient  DOH-009-MS  DOH-005-QZ         NaN  02/16/2020   

   AvgFlow   dur      Vol Field_note  ...    oc2    oc3    oc4  pyrolC    ec1  \
0     16.7  24.3  24.3486        NaN  ...  1.074  0.634  0.450   0.555  4.190   
1     16.7  24.2  24.2484        NaN  ...    NaN    NaN    NaN     NaN    NaN   
2     16.7  24.5  24.5490        NaN  ...  0.476  0.526  0.225   0.272  1.501   
3     16.7  24.5  24.5490        NaN  ...  0.584  0.258  0.183   0.258  1.738   
4     16.7  24.2  24.2484        NaN  ...  0.758  0.319  0.267   0.312  2.168   

     ec2    ec3  optEC   latitude  longitude  
0  0.408  0.022  1.247  25.325794  51.433138  
1    NaN    NaN    NaN  25.325794  51.433138  
2  0.161  0.014  0.572  25.325794  51.433138  
3  0.108  0.009  0.692  25.325794  51.433138  
4  0.149  0.010  0.796  25.325794  51.433138  

[5 rows x 128 columns]

In [13]:
qatar_pm25.shape

(190, 128)

In [14]:
qatar_pm25.columns.tolist()

['pms',
 'location',
 'sample_id',
 'sample_id1',
 'sample_type',
 'Start_Date',
 'AvgFlow',
 'dur',
 'Vol',
 'Field_note',
 'pm25',
 'pm10',
 'BC',
 'BrC',
 'DC',
 'Na',
 'Naunc',
 'Mg',
 'Mgunc',
 'Al',
 'Alunc',
 'Si',
 'Siunc',
 'P',
 'Punc',
 'S',
 'Sunc',
 'Cl',
 'Clunc',
 'K',
 'Kunc',
 'Ca',
 'Caunc',
 'Sc',
 'Scunc',
 'Ti',
 'Tiunc',
 'V',
 'Vunc',
 'Cr',
 'Crunc',
 'Mn',
 'Mnunc',
 'Fe',
 'Feunc',
 'Co',
 'Counc',
 'Ni',
 'Niunc',
 'Cu',
 'Cuunc',
 'Zn',
 'Znunc',
 'Ga',
 'Gaunc',
 'Ge',
 'Geunc',
 'As',
 'Asunc',
 'Se',
 'Seunc',
 'Br',
 'Brunc',
 'Rb',
 'Rbunc',
 'Sr',
 'Srunc',
 'Y',
 'Yunc',
 'Zr',
 'Zrunc',
 'Nb',
 'Nbunc',
 'Mo',
 'Mounc',
 'Pd',
 'Pdunc',
 'Ag',
 'Agunc',
 'Cd',
 'Cdunc',
 'In',
 'Inunc',
 'Sn',
 'Snunc',
 'Sb',
 'Sbunc',
 'Cs',
 'Csunc',
 'Ba',
 'Baunc',
 'La',
 'Launc',
 'Ce',
 'Ceunc',
 'Sm',
 'Smunc',
 'Eu',
 'Euunc',
 'Tb',
 'Tbunc',
 'W',
 'Wunc',
 'Au',
 'Auunc',
 'Hg',
 'Hgunc',
 'Tl',
 'Tlunc',
 'Pb',
 'Pbunc',
 'oc',
 'ocunc',
 'ec',
 'ecunc'

In [15]:
qatar_pm25.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 190 entries, 0 to 189
Columns: 128 entries, pms to longitude
dtypes: float64(121), object(7)
memory usage: 190.1+ KB


In [16]:
qatar_pm25['Start_Date'] = pd.to_datetime(qatar_pm25['Start_Date'])

In [17]:
qatar_pm25.head()

pms       location   sample_id  sample_id1 sample_type Start_Date  \
0  PM2.5  Qatar-Ambient  DOH-001-MS  DOH-001-QZ         NaN 2020-02-06   
1  PM2.5  Qatar-Ambient  DOH-005-MS         NaN         NaN 2020-02-10   
2  PM2.5  Qatar-Ambient  DOH-003-MS  DOH-002-QZ         NaN 2020-02-12   
3  PM2.5  Qatar-Ambient  DOH-007-MS  DOH-004-QZ         NaN 2020-02-14   
4  PM2.5  Qatar-Ambient  DOH-009-MS  DOH-005-QZ         NaN 2020-02-16   

   AvgFlow   dur      Vol Field_note  ...    oc2    oc3    oc4  pyrolC    ec1  \
0     16.7  24.3  24.3486        NaN  ...  1.074  0.634  0.450   0.555  4.190   
1     16.7  24.2  24.2484        NaN  ...    NaN    NaN    NaN     NaN    NaN   
2     16.7  24.5  24.5490        NaN  ...  0.476  0.526  0.225   0.272  1.501   
3     16.7  24.5  24.5490        NaN  ...  0.584  0.258  0.183   0.258  1.738   
4     16.7  24.2  24.2484        NaN  ...  0.758  0.319  0.267   0.312  2.168   

     ec2    ec3  optEC   latitude  longitude  
0  0.408  0.022  1.247  25.325794  51.433138  
1    NaN    NaN    NaN  25.325794  51.433138  
2  0.161  0.014  0.572  25.325794  51.433138  
3  0.108  0.009  0.692  25.325794  51.433138  
4  0.149  0.010  0.796  25.325794  51.433138  

[5 rows x 128 columns]

## Raw Kuwait

In [18]:
raw_kwt = pd.read_csv(data_dir + 'raw-kwt-2017-2020.csv')

In [19]:
raw_kwt.head()

date parameter  \
0  {utc=2017-08-11T05:00:00.000Z, local=2017-08-1...      pm25   
1  {utc=2017-08-13T13:00:00.000Z, local=2017-08-1...      pm25   
2  {utc=2017-08-12T16:00:00.000Z, local=2017-08-1...      pm25   
3  {utc=2017-08-10T22:00:00.000Z, local=2017-08-1...      pm25   
4  {utc=2017-08-12T09:00:00.000Z, local=2017-08-1...      pm25   

                          location  value   unit         city  \
0  US Diplomatic Post: Kuwait City   55.0  µg/m³  Kuwait City   
1  US Diplomatic Post: Kuwait City   57.0  µg/m³  Kuwait City   
2  US Diplomatic Post: Kuwait City   69.0  µg/m³  Kuwait City   
3  US Diplomatic Post: Kuwait City   41.0  µg/m³  Kuwait City   
4  US Diplomatic Post: Kuwait City   58.0  µg/m³  Kuwait City   

                                         attribution          averagingperiod  \
0  [{name=EPA AirNow DOS, url=http://airnow.gov/i...  {unit=hours, value=1.0}   
1  [{name=EPA AirNow DOS, url=http://airnow.gov/i...  {unit=hours, value=1.0}   
2  [{name=EPA AirNow DOS, url=http://airnow.gov/i...  {unit=hours, value=1.0}   
3  [{name=EPA AirNow DOS, url=http://airnow.gov/i...  {unit=hours, value=1.0}   
4  [{name=EPA AirNow DOS, url=http://airnow.gov/i...  {unit=hours, value=1.0}   

                                coordinates country           sourcename  \
0  {latitude=29.292316, longitude=48.04768}      KW  StateAir_KuwaitCity   
1  {latitude=29.292316, longitude=48.04768}      KW  StateAir_KuwaitCity   
2  {latitude=29.292316, longitude=48.04768}      KW  StateAir_KuwaitCity   
3  {latitude=29.292316, longitude=48.04768}      KW  StateAir_KuwaitCity   
4  {latitude=29.292316, longitude=48.04768}      KW  StateAir_KuwaitCity   

   sourcetype  mobile  
0  government   False  
1  government   False  
2  government   False  
3  government   False  
4  government   False

In [20]:
raw_kwt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25788 entries, 0 to 25787
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   date             25788 non-null  object 
 1   parameter        25788 non-null  object 
 2   location         25788 non-null  object 
 3   value            25788 non-null  float64
 4   unit             25788 non-null  object 
 5   city             25788 non-null  object 
 6   attribution      25788 non-null  object 
 7   averagingperiod  25788 non-null  object 
 8   coordinates      25788 non-null  object 
 9   country          25788 non-null  object 
 10  sourcename       25788 non-null  object 
 11  sourcetype       25788 non-null  object 
 12  mobile           25788 non-null  bool   
dtypes: bool(1), float64(1), object(11)
memory usage: 2.4+ MB


In [21]:
import re
from datetime import datetime

# Expressions régulières pour les deux formats
utc_pattern = r'(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})T(?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2}\.\d{3})Z'
local_pattern = r'(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})T(?P<hour>\d{2}):(?P<minute>\d{2}):(?P<second>\d{2})\+(?P<offset>\d{2}):(?P<offset_minute>\d{2})'

# Example strings
utc_string = '2017-08-11T05:00:00.000Z'
local_string = '2017-08-11T08:00:00+03:00'

# Function to parse datetime with regex
def parse_datetime_with_regex(date_string, pattern):
    match = re.match(pattern, date_string)
    if match:
        parts = match.groupdict()
        return datetime(
            int(parts['year']),
            int(parts['month']),
            int(parts['day']),
            int(parts['hour']),
            int(parts['minute']),
            int(float(parts['second'])),  # handling seconds with decimals
            int((float(parts['second']) - int(float(parts['second']))) * 1_000_000)  # microseconds
        )
    return None

# Parsing the UTC and local datetime strings
utc_datetime = parse_datetime_with_regex(utc_string, utc_pattern)
local_datetime = parse_datetime_with_regex(local_string, local_pattern)

print(f"UTC datetime: {utc_datetime}")
print(f"Local datetime: {local_datetime}")

UTC datetime: 2017-08-11 05:00:00
Local datetime: 2017-08-11 08:00:00


In [22]:
pd.to_datetime('2017-08-11T05:00:00.000Z')

Timestamp('2017-08-11 05:00:00+0000', tz='UTC')

In [23]:
pd.to_datetime('2017-08-11T08:00:00+03:00')

Timestamp('2017-08-11 08:00:00+0300', tz='UTC+03:00')

# MERRA-2

In [24]:
merra2 = xr.open_dataset(data_dir + 'MERRA2_aerosol_variables_over_MiddleEast_daily_20180101-20200531.nc')

In [25]:
merra2

<xarray.Dataset> Size: 381MB
Dimensions:    (y: 63, x: 78, time: 881)
Coordinates:
  * time       (time) datetime64[ns] 7kB 2018-01-01T12:00:00 ... 2020-05-31T1...
Dimensions without coordinates: y, x
Data variables: (12/13)
    lat        (y) float64 504B ...
    lon        (x) float64 624B ...
    BCEXTTAU   (time, y, x) float64 35MB ...
    DUEXTTAU   (time, y, x) float64 35MB ...
    OCEXTTAU   (time, y, x) float64 35MB ...
    SUEXTTAU   (time, y, x) float64 35MB ...
    ...         ...
    BCSMASS    (time, y, x) float64 35MB ...
    DUSMASS25  (time, y, x) float64 35MB ...
    DUSMASS    (time, y, x) float64 35MB ...
    OCSMASS    (time, y, x) float64 35MB ...
    SO4SMASS   (time, y, x) float64 35MB ...
    SSSMASS    (time, y, x) float64 35MB ...

In [26]:
merra2['lat'].values

array([11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. ])

In [27]:
merra2['lon'].values

array([26.25 , 26.875, 27.5  , 28.125, 28.75 , 29.375, 30.   , 30.625,
       31.25 , 31.875, 32.5  , 33.125, 33.75 , 34.375, 35.   , 35.625,
       36.25 , 36.875, 37.5  , 38.125, 38.75 , 39.375, 40.   , 40.625,
       41.25 , 41.875, 42.5  , 43.125, 43.75 , 44.375, 45.   , 45.625,
       46.25 , 46.875, 47.5  , 48.125, 48.75 , 49.375, 50.   , 50.625,
       51.25 , 51.875, 52.5  , 53.125, 53.75 , 54.375, 55.   , 55.625,
       56.25 , 56.875, 57.5  , 58.125, 58.75 , 59.375, 60.   , 60.625,
       61.25 , 61.875, 62.5  , 63.125, 63.75 , 64.375, 65.   , 65.625,
       66.25 , 66.875, 67.5  , 68.125, 68.75 , 69.375, 70.   , 70.625,
       71.25 , 71.875, 72.5  , 73.125, 73.75 , 74.375])

In [28]:
merra2['BCSMASS']

<xarray.DataArray 'BCSMASS' (time: 881, y: 63, x: 78)> Size: 35MB
[4329234 values with dtype=float64]
Coordinates:
  * time     (time) datetime64[ns] 7kB 2018-01-01T12:00:00 ... 2020-05-31T12:...
Dimensions without coordinates: y, x
Attributes:
    units:    kg m-3

In [ ]:
merra2['BCSMASS'].sel(time='2018-01-01T12:00:00', y=20, x=40).values

NameError: name 'merra2' is not defined

In [30]:
merra2['lat'].values

array([11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
       27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5, 31. , 31.5, 32. , 32.5,
       33. , 33.5, 34. , 34.5, 35. , 35.5, 36. , 36.5, 37. , 37.5, 38. ,
       38.5, 39. , 39.5, 40. , 40.5, 41. , 41.5, 42. ])

In [31]:
merra2['lon'].values

array([26.25 , 26.875, 27.5  , 28.125, 28.75 , 29.375, 30.   , 30.625,
       31.25 , 31.875, 32.5  , 33.125, 33.75 , 34.375, 35.   , 35.625,
       36.25 , 36.875, 37.5  , 38.125, 38.75 , 39.375, 40.   , 40.625,
       41.25 , 41.875, 42.5  , 43.125, 43.75 , 44.375, 45.   , 45.625,
       46.25 , 46.875, 47.5  , 48.125, 48.75 , 49.375, 50.   , 50.625,
       51.25 , 51.875, 52.5  , 53.125, 53.75 , 54.375, 55.   , 55.625,
       56.25 , 56.875, 57.5  , 58.125, 58.75 , 59.375, 60.   , 60.625,
       61.25 , 61.875, 62.5  , 63.125, 63.75 , 64.375, 65.   , 65.625,
       66.25 , 66.875, 67.5  , 68.125, 68.75 , 69.375, 70.   , 70.625,
       71.25 , 71.875, 72.5  , 73.125, 73.75 , 74.375])

In [32]:
merra2.data_vars

Data variables:
    lat        (y) float64 504B 11.0 11.5 12.0 12.5 13.0 ... 40.5 41.0 41.5 42.0
    lon        (x) float64 624B 26.25 26.88 27.5 28.12 ... 73.12 73.75 74.38
    BCEXTTAU   (time, y, x) float64 35MB ...
    DUEXTTAU   (time, y, x) float64 35MB ...
    OCEXTTAU   (time, y, x) float64 35MB ...
    SUEXTTAU   (time, y, x) float64 35MB ...
    TOTEXTTAU  (time, y, x) float64 35MB ...
    BCSMASS    (time, y, x) float64 35MB ...
    DUSMASS25  (time, y, x) float64 35MB ...
    DUSMASS    (time, y, x) float64 35MB ...
    OCSMASS    (time, y, x) float64 35MB ...
    SO4SMASS   (time, y, x) float64 35MB ...
    SSSMASS    (time, y, x) float64 35MB ...

# Kuwait MERRA-2

In [33]:
kwt_merra2 = pyreadr.read_r(data_dir + 'kwt-merra2-2004-2017.rds')[None]

In [34]:
kwt_merra2.head()

merra_id     lon   lat        date  BCEXTTAU  DUEXTTAU  OCEXTTAU  SUEXTTAU  \
0      2843  47.500  29.0  2004-02-20  0.006659  0.169699  0.015269  0.040475   
1      2844  48.125  29.0  2004-02-20  0.006504  0.166168  0.016589  0.061543   
2      2921  47.500  29.5  2004-02-20  0.006850  0.149209  0.013217  0.033773   
3      2999  47.500  30.0  2004-02-20  0.006949  0.130888  0.012205  0.031641   
4      3000  48.125  30.0  2004-02-20  0.006471  0.121943  0.013900  0.037659   

   TOTEXTTAU       BCSMASS     DUSMASS25       DUSMASS       OCSMASS  \
0   0.283420  4.083631e-10  3.648772e-08  4.832667e-07  8.607799e-10   
1   0.315893  4.061865e-10  4.671589e-08  5.143811e-07  9.973273e-10   
2   0.271884  4.369151e-10  4.143324e-08  5.468925e-07  9.154349e-10   
3   0.255173  4.479688e-10  4.474229e-08  5.500915e-07  9.726004e-10   
4   0.255255  4.625965e-10  5.033568e-08  4.517666e-07  1.030353e-09   

       SO4SMASS       SSSMASS  
0  3.609488e-09  1.079638e-09  
1  6.877908e-09  2.751014e-09  
2  3.315608e-09  1.332174e-09  
3  3.039766e-09  9.280079e-10  
4  2.533897e-09  1.551448e-09

# Middle East MERRA-2

In [35]:
me_merra2 = pyreadr.read_r(data_dir + 'me-merra2-2004-2020.rds')[None]

In [36]:
me_merra2.head()

merra_id        date  BCEXTTAU  DUEXTTAU  OCEXTTAU  SUEXTTAU  TOTEXTTAU  \
0      2074  2004-02-20  0.006866  0.650480  0.017735  0.059926   0.754369   
1      2074  2004-02-24  0.006688  0.316658  0.013308  0.048836   0.423348   
2      2074  2004-02-25  0.005344  0.186273  0.008649  0.031994   0.265613   
3      2074  2004-02-26  0.004411  0.158159  0.006140  0.019677   0.219963   
4      2074  2004-02-27  0.004975  0.118688  0.006352  0.021444   0.170210   

        BCSMASS     DUSMASS25       DUSMASS       OCSMASS      SO4SMASS  \
0  5.773965e-10  9.504220e-08  3.950336e-07  5.584915e-10  2.955050e-09   
1  3.028902e-10  9.930409e-08  4.456063e-07  4.539515e-10  2.320846e-09   
2  2.358363e-10  6.737961e-08  3.705403e-07  2.697813e-10  1.427109e-09   
3  2.476195e-10  8.232504e-08  4.145744e-07  4.220488e-10  1.418632e-09   
4  3.342038e-10  4.153299e-08  1.764468e-07  6.266703e-10  1.575010e-09   

        SSSMASS  merra_lon  merra_lat  
0  1.360088e-08     54.375       24.0  
1  5.531971e-08     54.375       24.0  
2  6.401208e-08     54.375       24.0  
3  5.769289e-08     54.375       24.0  
4  2.589211e-08     54.375       24.0

# MERRA-2 Climatology

In [37]:
merra2_climatology = xr.open_dataset(data_dir + 'MERRA2_aerosol_variables_over_MiddleEast_daily_climatology_2000-2018.nc')

In [38]:
merra2_climatology

<xarray.Dataset> Size: 158MB
Dimensions:    (time: 365, y: 63, x: 78)
Coordinates:
  * time       (time) datetime64[ns] 3kB 2017-01-01T12:00:00 ... 2017-12-31T1...
Dimensions without coordinates: y, x
Data variables: (12/13)
    lat        (y) float64 504B ...
    lon        (x) float64 624B ...
    BCEXTTAU   (time, y, x) float64 14MB ...
    DUEXTTAU   (time, y, x) float64 14MB ...
    OCEXTTAU   (time, y, x) float64 14MB ...
    SUEXTTAU   (time, y, x) float64 14MB ...
    ...         ...
    BCSMASS    (time, y, x) float64 14MB ...
    DUSMASS25  (time, y, x) float64 14MB ...
    DUSMASS    (time, y, x) float64 14MB ...
    OCSMASS    (time, y, x) float64 14MB ...
    SO4SMASS   (time, y, x) float64 14MB ...
    SSSMASS    (time, y, x) float64 14MB ...
Attributes:
    CDI:          Climate Data Interface version 1.7.2 (http://mpimet.mpg.de/...
    Conventions:  CF-1.4
    history:      Tue Nov 05 21:50:17 2019: cdo ydaymean MERRA2_aerosol_varia...
    CDO:          Climate Data Operators version 1.7.2 (http://mpimet.mpg.de/...

# Middle East MERRA-2 Dust

In [39]:
me_merra2_dust = pyreadr.read_r(data_dir + 'me-merra2-dust-2004-2020.rds')[None]

In [40]:
me_merra2_dust.head()

merra_id        date     DUSMASS25       DUSMASS  merra_lon  merra_lat
0      2074  2004-02-20  9.504220e-08  3.950336e-07     54.375       24.0
1      2074  2004-02-24  9.930409e-08  4.456063e-07     54.375       24.0
2      2074  2004-02-25  6.737961e-08  3.705403e-07     54.375       24.0
3      2074  2004-02-26  8.232504e-08  4.145744e-07     54.375       24.0
4      2074  2004-02-27  4.153299e-08  1.764468e-07     54.375       24.0

In [41]:
me_merra2_dust.shape

(30413, 6)

In [42]:
min(me_merra2_dust['merra_lon'])

44.375

In [43]:
min(me_merra2_dust['merra_lat'])

24.0

In [44]:
max(me_merra2_dust['merra_lon'])

55.625

In [45]:
max(me_merra2_dust['merra_lat'])

33.5

# G5NR

In [46]:
g5nr = xr.open_dataset(data_dir + 'G5NR_aerosol_variables_over_MiddleEast_daily_20050516-20060515.nc')

In [47]:
g5nr

<xarray.Dataset> Size: 13GB
Dimensions:    (y: 499, x: 788, time: 365)
Coordinates:
  * time       (time) datetime64[ns] 3kB 2005-05-16T12:00:00 ... 2006-05-15T1...
Dimensions without coordinates: y, x
Data variables: (12/13)
    lat        (y) float64 4kB ...
    lon        (x) float64 6kB ...
    BCEXTTAU   (time, y, x) float64 1GB ...
    DUEXTTAU   (time, y, x) float64 1GB ...
    OCEXTTAU   (time, y, x) float64 1GB ...
    SUEXTTAU   (time, y, x) float64 1GB ...
    ...         ...
    BCSMASS    (time, y, x) float64 1GB ...
    DUSMASS25  (time, y, x) float64 1GB ...
    DUSMASS    (time, y, x) float64 1GB ...
    OCSMASS    (time, y, x) float64 1GB ...
    SO4SMASS   (time, y, x) float64 1GB ...
    SSSMASS    (time, y, x) float64 1GB ...

In [48]:
g5nr['lat'].values

array([10.9375, 11.    , 11.0625, 11.125 , 11.1875, 11.25  , 11.3125,
       11.375 , 11.4375, 11.5   , 11.5625, 11.625 , 11.6875, 11.75  ,
       11.8125, 11.875 , 11.9375, 12.    , 12.0625, 12.125 , 12.1875,
       12.25  , 12.3125, 12.375 , 12.4375, 12.5   , 12.5625, 12.625 ,
       12.6875, 12.75  , 12.8125, 12.875 , 12.9375, 13.    , 13.0625,
       13.125 , 13.1875, 13.25  , 13.3125, 13.375 , 13.4375, 13.5   ,
       13.5625, 13.625 , 13.6875, 13.75  , 13.8125, 13.875 , 13.9375,
       14.    , 14.0625, 14.125 , 14.1875, 14.25  , 14.3125, 14.375 ,
       14.4375, 14.5   , 14.5625, 14.625 , 14.6875, 14.75  , 14.8125,
       14.875 , 14.9375, 15.    , 15.0625, 15.125 , 15.1875, 15.25  ,
       15.3125, 15.375 , 15.4375, 15.5   , 15.5625, 15.625 , 15.6875,
       15.75  , 15.8125, 15.875 , 15.9375, 16.    , 16.0625, 16.125 ,
       16.1875, 16.25  , 16.3125, 16.375 , 16.4375, 16.5   , 16.5625,
       16.625 , 16.6875, 16.75  , 16.8125, 16.875 , 16.9375, 17.    ,
       17.0625, 17.1

In [49]:
g5nr['lon'].values

array([25.6875, 25.75  , 25.8125, 25.875 , 25.9375, 26.    , 26.0625,
       26.125 , 26.1875, 26.25  , 26.3125, 26.375 , 26.4375, 26.5   ,
       26.5625, 26.625 , 26.6875, 26.75  , 26.8125, 26.875 , 26.9375,
       27.    , 27.0625, 27.125 , 27.1875, 27.25  , 27.3125, 27.375 ,
       27.4375, 27.5   , 27.5625, 27.625 , 27.6875, 27.75  , 27.8125,
       27.875 , 27.9375, 28.    , 28.0625, 28.125 , 28.1875, 28.25  ,
       28.3125, 28.375 , 28.4375, 28.5   , 28.5625, 28.625 , 28.6875,
       28.75  , 28.8125, 28.875 , 28.9375, 29.    , 29.0625, 29.125 ,
       29.1875, 29.25  , 29.3125, 29.375 , 29.4375, 29.5   , 29.5625,
       29.625 , 29.6875, 29.75  , 29.8125, 29.875 , 29.9375, 30.    ,
       30.0625, 30.125 , 30.1875, 30.25  , 30.3125, 30.375 , 30.4375,
       30.5   , 30.5625, 30.625 , 30.6875, 30.75  , 30.8125, 30.875 ,
       30.9375, 31.    , 31.0625, 31.125 , 31.1875, 31.25  , 31.3125,
       31.375 , 31.4375, 31.5   , 31.5625, 31.625 , 31.6875, 31.75  ,
       31.8125, 31.8